# Generated by Django 5.1.6 on 2025-08-26 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockbatch',
            name='unique_active_batch_per_product',
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_status', 'active')), fields=('user', 'product'), name='unique_active_batch_per_user_product'),
        ),
    ]
