# Generated by Django 5.1.6 on 2025-09-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockbatch_original_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='original_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
