# Generated by Django 5.1.6 on 2025-09-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        ('inventory', '0004_alter_stockbatch_original_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Broker who facilitated this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='broker.broker'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='broker_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated commission amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='broker_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage for this transaction (e.g., 2.50 for 2.5%)', max_digits=5),
        ),
    ]
