# Generated by Django 5.1.6 on 2025-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stockbatch_updated_at_stockbatch_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='broker_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
