# Generated by Django 5.1.6 on 2025-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockbatch_broker_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
