# Generated by Django 5.1.6 on 2025-09-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockbatch_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='broker_commission_percent',
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='broker_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission paid to broker for this batch (Rupees)', max_digits=10),
        ),
    ]
