# Generated by Django 5.1.6 on 2025-09-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockbatch_broker_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='broker_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission paid to broker for this batch (Rupees)', max_digits=10),
        ),
    ]
