# Generated by Django 5.1.6 on 2025-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockbatch_broker_commission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='labour_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='varne_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
