# Generated by Django 5.1.6 on 2025-09-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_rename_default_commission_percent_broker_default_commission_amount'),
        ('inventory', '0011_stockbatch_labour_cost_stockbatch_varne_cost'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='original_quantity',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='vendor_invoice',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='transport.transporter'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='transporter_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='weight_unit',
            field=models.CharField(choices=[('bags', 'Bags'), ('tonnes', 'Tonnes')], default='bags', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='broker.broker'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='broker_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
