# Generated by Django 5.1.6 on 2025-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_stockbatch_original_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='original_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
