# Generated by Django 5.1.6 on 2025-09-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stockbatch_original_quantity_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='vendor_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='vendors.vendorinvoice'),
        ),
    ]
