# Generated by Django 5.1.6 on 2026-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockentry_delete_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='cgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='sgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
