# Generated by Django 5.1.6 on 2026-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_cgst_sgst_percentage_to_stockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='broker_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Commission per bag/unit (e.g. 5 for ₹5 per bag)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='broker_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total commission = rate × quantity (auto-calculated)', max_digits=10, null=True),
        ),
    ]
