export const admin_routes = {
  home: "/admin/home",
  users: "/admin/users",
  // allusers: "/users/all",
  roles: "/admin/roles",
  rolepermissions: "admin/role-permissions/:roleID",
  allcategories: "/admin/categories",
  allproducts: "/admin/products",
  allusersdata: "/admin/all-users-data",
  allstockmanagement: "/admin/stock-management",
  adminsalesreport: "/admin/reports/sales",
  adminpurchasereport: "/admin/reports/purchase",
  adminbrokerreport: "/admin/reports/broker",
  admintransporterreport: "/admin/reports/transporter",
  adminfranchisereport: "/admin/reports/franchise",
};
