# Generated by Django 5.1.6 on 2025-08-28 10:24

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwnerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=shop.models.generate_shop_order_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('order_placed', 'Sent to Managers'), ('partially_fulfilled', 'Partially Fulfilled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fulfilled_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfilled_shop_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.shopownerorders')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwnerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owned_products', to=settings.AUTH_USER_MODEL)),
                ('source_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_sold_to_shop_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('manager_response_notes', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_requests', to='shop.shoporderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['manager', 'status'], name='shop_manage_manager_244f2b_idx'), models.Index(fields=['order_item', 'status'], name='shop_manage_order_i_aeb25a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shopownerorders',
            index=models.Index(fields=['shop_owner', 'status'], name='shop_shopow_shop_ow_389815_idx'),
        ),
        migrations.AddIndex(
            model_name='shopownerorders',
            index=models.Index(fields=['order_number'], name='shop_shopow_order_n_c4d82c_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoporderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_per_shop_order'),
        ),
        migrations.AddIndex(
            model_name='shopownerproducts',
            index=models.Index(fields=['shop_owner', 'product'], name='shop_shopow_shop_ow_f9c2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='shopownerproducts',
            index=models.Index(fields=['source_manager'], name='shop_shopow_source__ac1a4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopownerproducts',
            constraint=models.UniqueConstraint(fields=('shop_owner', 'product'), name='unique_shop_owner_product'),
        ),
    ]
