# Generated by Django 5.1.6 on 2025-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopownerorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopownerproducts',
            name='delivery_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopownerproducts',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopownerorders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('order_placed', 'Order Placed'), ('partially_fulfilled', 'Partially Fulfilled'), ('delivery_in_progress', 'Delivery in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
