# Generated by Django 5.1.6 on 2026-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopownerproducts_delivery_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopownerorders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('order_placed', 'Order Placed'), ('partially_fulfilled', 'Partially Fulfilled'), ('delivery_in_progress', 'Delivery in Progress'), ('packing', 'Packing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
