# Generated by Django 5.1.6 on 2026-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopownerorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopownerproducts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
