# Generated by Django 5.1.6 on 2026-04-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopownerorders_payment_fields'),
        ('transport', '0004_transporter_license_number_transporter_rc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopownerorders',
            name='delivery_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopownerorders',
            name='delivery_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopownerorders',
            name='delivery_transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_deliveries', to='transport.transporter'),
        ),
        migrations.AddField(
            model_name='shopownerorders',
            name='delivery_transporter_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
