# Generated by Django 5.1.6 on 2026-04-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shoppaymenttransaction'),
        ('transport', '0004_transporter_license_number_transporter_rc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderitem',
            name='item_delivery_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoporderitem',
            name='item_delivery_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoporderitem',
            name='item_delivery_transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_deliveries', to='transport.transporter'),
        ),
        migrations.AddField(
            model_name='shoporderitem',
            name='item_delivery_transporter_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shoporderitem',
            name='manager_status',
            field=models.CharField(blank=True, choices=[('order_placed', 'Order Placed'), ('packing', 'Packing'), ('delivery_in_progress', 'Delivery in Progress'), ('cancelled', 'Cancelled')], max_length=30, null=True),
        ),
    ]
