# Generated by Django 5.1.6 on 2026-04-23 10:45

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shoppaymenttransaction_manager'),
        ('transport', '0004_transporter_license_number_transporter_rc_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S2SOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=shop.models.generate_s2s_order_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('partially_accepted', 'Partially Accepted'), ('accepted', 'Accepted'), ('packing', 'Packing'), ('delivery_in_progress', 'Delivery in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='order_placed', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('mix', 'Mix')], max_length=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_from', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_to', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_transporter_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2s_purchases', to=settings.AUTH_USER_MODEL)),
                ('delivery_transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s2s_deliveries', to='transport.transporter')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2s_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='S2SOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('fulfilled_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.s2sorder')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2s_order_items', to='shop.shopownerproducts')),
            ],
        ),
        migrations.CreateModel(
            name='S2SPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('mix', 'Mix')], max_length=20, null=True)),
                ('online_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('offline_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='shop.s2sorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_s2s_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='s2sorder',
            index=models.Index(fields=['buyer', 'status'], name='shop_s2sord_buyer_i_20aee1_idx'),
        ),
        migrations.AddIndex(
            model_name='s2sorder',
            index=models.Index(fields=['seller', 'status'], name='shop_s2sord_seller__6f9bb3_idx'),
        ),
    ]
