# Generated by Django 5.1.6 on 2025-09-29 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('transporter_name__isnull', False), models.Q(('transporter_name', ''), _negated=True)), fields=('user', 'transporter_name'), name='unique_transporter_name_per_user'), models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('user', 'email'), name='unique_transporter_email_per_user'), models.UniqueConstraint(condition=models.Q(('contact_number__isnull', False), models.Q(('contact_number', ''), _negated=True)), fields=('user', 'contact_number'), name='unique_transporter_contact_per_user'), models.UniqueConstraint(condition=models.Q(('gst_number__isnull', False), models.Q(('gst_number', ''), _negated=True)), fields=('user', 'gst_number'), name='unique_transporter_gst_per_user'), models.UniqueConstraint(condition=models.Q(('pan_number__isnull', False), models.Q(('pan_number', ''), _negated=True)), fields=('user', 'pan_number'), name='unique_transporter_pan_per_user'), models.UniqueConstraint(condition=models.Q(('registration_number__isnull', False), models.Q(('registration_number', ''), _negated=True)), fields=('user', 'registration_number'), name='unique_transporter_reg_per_user'), models.UniqueConstraint(condition=models.Q(('account_number__isnull', False), models.Q(('account_number', ''), _negated=True)), fields=('user', 'account_number'), name='unique_transporter_acc_per_user'), models.UniqueConstraint(condition=models.Q(('upi_id__isnull', False), models.Q(('upi_id', ''), _negated=True)), fields=('user', 'upi_id'), name='unique_transporter_upi_per_user')],
            },
        ),
    ]
