# Generated by Django 5.1.6 on 2025-09-29 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transporter',
            name='unique_transporter_reg_per_user',
        ),
        migrations.RenameField(
            model_name='transporter',
            old_name='registration_number',
            new_name='vehicle_number',
        ),
        migrations.AddConstraint(
            model_name='transporter',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_number__isnull', False), models.Q(('vehicle_number', ''), _negated=True)), fields=('user', 'vehicle_number'), name='unique_transporter_reg_per_user'),
        ),
    ]
