# Generated by Django 5.1.6 on 2026-03-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transporter_unique_transporter_reg_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transporter',
            name='unique_transporter_name_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='transporter',
            name='unique_transporter_gst_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='transporter',
            name='unique_transporter_pan_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='transporter',
            name='unique_transporter_acc_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='transporter',
            name='unique_transporter_upi_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='transporter',
            name='unique_transporter_reg_per_user',
        ),
        migrations.AlterField(
            model_name='transporter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
