# Generated by Django 5.1.6 on 2026-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_remove_transporter_unique_transporter_name_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='rc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
