# Generated by Django 5.1.6 on 2025-09-09 05:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Default commission percentage (e.g., 2.50 for 2.5%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_brokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['broker_name'],
                'indexes': [models.Index(fields=['broker_name', 'is_active'], name='broker_brok_broker__b04c1a_idx'), models.Index(fields=['created_by', 'is_active'], name='broker_brok_created_043dfb_idx')],
            },
        ),
    ]
