# Generated by Django 5.1.6 on 2025-09-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='default_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default commission percentage (e.g., 4 for 4₹)', max_digits=10),
        ),
    ]
