# Generated by Django 5.1.6 on 2025-09-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_alter_broker_default_commission_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='default_commission_percent',
            new_name='default_commission_amount',
        ),
    ]
