export const admin_modules = {
  home: "adminhome",
  rolepermissions: "rolepermissions",
  roles: "roles",
  users: "users",
  // allusers: "allusers",
  allcategories: "allcategories",
  allproducts: "allproducts",
  adminreports: "adminreports",
  allusersdata: "allusersdata",
  allstockmanagement: "allstockmanagement",
  adminsalesreport: "adminsalesreport",
  adminpurchasereport: "adminpurchasereport",
  adminbrokerreport: "adminbrokerreport",
  adminfranchisereport: "adminfranchisereport",
};
