# Generated by Django 5.1.6 on 2025-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g., 18 for 18%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount in rupees', max_digits=10),
        ),
    ]
