# Generated by Django 5.1.6 on 2025-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posorders', '0002_posorder_tax_percentage_alter_posorder_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='labour_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='transport_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
