# Generated by Django 5.1.6 on 2026-03-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posorders', '0003_posorder_labour_charges_posorder_transport_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorderitem',
            name='original_stock_batch',
        ),
    ]
