# Generated by Django 5.1.6 on 2026-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posorders', '0004_remove_posorderitem_original_stock_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='posorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='cgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='posorder',
            name='offline_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='online_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posorder',
            name='sgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit'), ('mix', 'Mix')], max_length=20, null=True),
        ),
    ]
