# Generated by Django 5.1.6 on 2025-08-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_permission', models.CharField(max_length=100)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rolemaster')),
            ],
            options={
                'unique_together': {('user_role', 'module_permission')},
            },
        ),
    ]
