# Generated by Django 5.1.6 on 2026-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
