# Generated by Django 5.1.6 on 2026-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight of one bag/unit in kg (e.g. 50 for a 50 kg bag)', max_digits=8, null=True),
        ),
    ]
