# Generated by Django 5.1.6 on 2026-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
