# Generated by Django 5.1.6 on 2025-09-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_email',
        ),
    ]
