# Generated by Django 5.1.6 on 2025-10-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_unique_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type_of_customer',
            field=models.CharField(blank=True, choices=[('Customer A', 'Customer A'), ('Customer B', 'Customer B'), ('Customer C', 'Customer C')], max_length=20, null=True),
        ),
    ]
