# Generated by Django 5.1.6 on 2025-11-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_type_of_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type_of_customer',
            field=models.CharField(blank=True, choices=[('dairy', 'Dairy'), ('distributor_dealer', 'Distributor/Dealer'), ('farmer', 'Farmer')], max_length=20, null=True),
        ),
    ]
