# Generated by Django 5.1.6 on 2026-04-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_type_of_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='competitor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='competitor_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='competitor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='milk_collection',
            field=models.FloatField(blank=True, help_text='Milk collection in liters', null=True),
        ),
        migrations.CreateModel(
            name='CustomerAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_entries', to='customers.animaltype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='customers.customer')),
            ],
            options={
                'unique_together': {('customer', 'animal_type')},
            },
        ),
    ]
