# Generated by Django 5.1.6 on 2026-03-30 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_vendor_name_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_email_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_contact_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_gst_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_pan_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_reg_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_acc_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_upi_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_self_vendor_per_user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_self',
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('user', 'email'), name='unique_vendor_email_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_number__isnull', False), models.Q(('contact_number', ''), _negated=True)), fields=('user', 'contact_number'), name='unique_vendor_contact_per_user'),
        ),
    ]
